schema: ${INDEXER_API_URL}
documents: "./app/models/indexer/*.graphqls"
generates:
  ./app/models/indexer/sdk.ts:
    overwrite: true
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
    hooks:
      afterOneFileWrite: 'sed -i "" "s/graphql-request\/dist/graphql-request\/src/g"'
